# Generated by Django 5.2.6 on 2025-10-12 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0002_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="paidUser",
            field=models.BooleanField(default=False),
        ),
    ]
