# Generated by Django 5.2.6 on 2025-10-13 01:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0003_userprofile_paiduser"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="theme",
            field=models.CharField(
                choices=[
                    ("default", "Default (Green Matrix)"),
                    ("greydom", "Greydom (Dark Grey-Blue)"),
                    ("cloud", "Cloud (White & Dark Grey)"),
                    ("chaos", "Chaos (Black & Grey)"),
                    ("lebron", "LeBron (Premium)"),
                ],
                default="default",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="pythoncodesession",
            index=models.Index(
                fields=["user", "-updated_at"], name="homepage_py_user_id_51db7a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pythoncodesession",
            index=models.Index(
                fields=["user", "filename"], name="homepage_py_user_id_3adecf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pythoncodesession",
            index=models.Index(
                fields=["-created_at"], name="homepage_py_created_eae055_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userfiles",
            index=models.Index(
                fields=["user", "filename"], name="homepage_us_user_id_1a9afe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userfiles",
            index=models.Index(
                fields=["user", "is_system_file"], name="homepage_us_user_id_885d5b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userfiles",
            index=models.Index(
                fields=["-created_at"], name="homepage_us_created_2e9d5c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(fields=["user"], name="homepage_us_user_id_b99544_idx"),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(
                fields=["paidUser"], name="homepage_us_paidUse_a39ba1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(
                fields=["-created_at"], name="homepage_us_created_72fc4e_idx"
            ),
        ),
    ]
