# Generated by Django 5.2.6 on 2025-10-14 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0005_add_new_features"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="executionhistory",
            new_name="homepage_ex_user_id_4a88f3_idx",
            old_name="homepage_ex_user_id_9a8c76_idx",
        ),
        migrations.RenameIndex(
            model_name="executionhistory",
            new_name="homepage_ex_user_id_b516a6_idx",
            old_name="homepage_ex_user_id_7e9b45_idx",
        ),
        migrations.RenameIndex(
            model_name="executionhistory",
            new_name="homepage_ex_execute_90b298_idx",
            old_name="homepage_ex_execute_3f2a1c_idx",
        ),
        migrations.RenameIndex(
            model_name="sharedcode",
            new_name="homepage_sh_share_i_914925_idx",
            old_name="homepage_sh_share_i_4a5b2e_idx",
        ),
        migrations.RenameIndex(
            model_name="sharedcode",
            new_name="homepage_sh_user_id_8337b9_idx",
            old_name="homepage_sh_user_id_6c8d3f_idx",
        ),
        migrations.RenameIndex(
            model_name="sharedcode",
            new_name="homepage_sh_is_publ_baf0e4_idx",
            old_name="homepage_sh_is_publ_7d9e4a_idx",
        ),
        migrations.RenameIndex(
            model_name="sharedcode",
            new_name="homepage_sh_view_co_6755cc_idx",
            old_name="homepage_sh_view_co_8e0f5b_idx",
        ),
    ]
