# Generated by Django 5.2.6 on 2025-10-15 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0009_add_profile_info"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="directmessage",
            new_name="homepage_di_sender__e8de1a_idx",
            old_name="homepage_di_sender__7a8b9c_idx",
        ),
        migrations.RenameIndex(
            model_name="directmessage",
            new_name="homepage_di_recipie_87b94a_idx",
            old_name="homepage_di_recipie_1e2f3g_idx",
        ),
        migrations.RenameIndex(
            model_name="directmessage",
            new_name="homepage_di_created_b1f709_idx",
            old_name="homepage_di_created_5h6i7j_idx",
        ),
        migrations.RenameIndex(
            model_name="executionhistory",
            new_name="homepage_ex_user_id_4a88f3_idx",
            old_name="homepage_ex_user_id_9a8c76_idx",
        ),
        migrations.RenameIndex(
            model_name="executionhistory",
            new_name="homepage_ex_user_id_b516a6_idx",
            old_name="homepage_ex_user_id_7e9b45_idx",
        ),
        migrations.RenameIndex(
            model_name="executionhistory",
            new_name="homepage_ex_execute_90b298_idx",
            old_name="homepage_ex_execute_3f2a1c_idx",
        ),
        migrations.RenameIndex(
            model_name="friendship",
            new_name="homepage_fr_from_us_4298ec_idx",
            old_name="homepage_fr_from_us_9f5b15_idx",
        ),
        migrations.RenameIndex(
            model_name="friendship",
            new_name="homepage_fr_to_user_134bee_idx",
            old_name="homepage_fr_to_user_a7c8e6_idx",
        ),
        migrations.RenameIndex(
            model_name="friendship",
            new_name="homepage_fr_created_a9b52d_idx",
            old_name="homepage_fr_created_4d92f1_idx",
        ),
        migrations.RenameIndex(
            model_name="sessionmember",
            new_name="homepage_se_session_124202_idx",
            old_name="homepage_se_session_online_idx",
        ),
        migrations.RenameIndex(
            model_name="sessionmember",
            new_name="homepage_se_user_id_6053c5_idx",
            old_name="homepage_se_user_active_idx",
        ),
        migrations.RenameIndex(
            model_name="sharedcode",
            new_name="homepage_sh_share_i_914925_idx",
            old_name="homepage_sh_share_i_4a5b2e_idx",
        ),
        migrations.RenameIndex(
            model_name="sharedcode",
            new_name="homepage_sh_user_id_8337b9_idx",
            old_name="homepage_sh_user_id_6c8d3f_idx",
        ),
        migrations.RenameIndex(
            model_name="sharedcode",
            new_name="homepage_sh_is_publ_baf0e4_idx",
            old_name="homepage_sh_is_publ_7d9e4a_idx",
        ),
        migrations.RenameIndex(
            model_name="sharedcode",
            new_name="homepage_sh_view_co_6755cc_idx",
            old_name="homepage_sh_view_co_8e0f5b_idx",
        ),
        migrations.RenameIndex(
            model_name="sharedcode",
            new_name="homepage_sh_session_539be1_idx",
            old_name="homepage_sh_session_idx",
        ),
        migrations.RenameIndex(
            model_name="userstatus",
            new_name="homepage_us_is_onli_fa13a1_idx",
            old_name="homepage_us_is_onli_8k9l0m_idx",
        ),
    ]
