# Generated by Django 5.2.6 on 2025-10-15 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0009_add_profile_info"),
    ]

    operations = []
