# Generated by Django 5.2.6 on 2025-10-16 14:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_auto_20251015_1231'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IDEDirectory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('path', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'IDE directories',
                'ordering': ['path', 'name'],
            },
        ),
        migrations.CreateModel(
            name='IDEExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_snippet', models.TextField()),
                ('output', models.TextField(blank=True)),
                ('error', models.TextField(blank=True)),
                ('execution_time', models.FloatField(default=0)),
                ('was_successful', models.BooleanField(default=True)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-executed_at'],
            },
        ),
        migrations.CreateModel(
            name='IDEFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('path', models.CharField(max_length=500)),
                ('content', models.TextField(default='')),
                ('file_type', models.CharField(choices=[('python', 'Python'), ('text', 'Text'), ('json', 'JSON'), ('csv', 'CSV'), ('markdown', 'Markdown'), ('html', 'HTML'), ('css', 'CSS'), ('javascript', 'JavaScript'), ('other', 'Other')], default='python', max_length=20)),
                ('size', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['path', 'name'],
            },
        ),
        migrations.CreateModel(
            name='IDEProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_accessed', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-last_accessed', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='IDETerminalSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('history', models.JSONField(default=list)),
                ('environment_vars', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_active', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_active'],
            },
        ),
        migrations.RenameIndex(
            model_name='directmessage',
            new_name='homepage_di_sender__e8de1a_idx',
            old_name='homepage_di_sender__7a8b9c_idx',
        ),
        migrations.RenameIndex(
            model_name='directmessage',
            new_name='homepage_di_recipie_87b94a_idx',
            old_name='homepage_di_recipie_1e2f3g_idx',
        ),
        migrations.RenameIndex(
            model_name='directmessage',
            new_name='homepage_di_created_b1f709_idx',
            old_name='homepage_di_created_5h6i7j_idx',
        ),
        migrations.RenameIndex(
            model_name='executionhistory',
            new_name='homepage_ex_user_id_4a88f3_idx',
            old_name='homepage_ex_user_id_9a8c76_idx',
        ),
        migrations.RenameIndex(
            model_name='executionhistory',
            new_name='homepage_ex_user_id_b516a6_idx',
            old_name='homepage_ex_user_id_7e9b45_idx',
        ),
        migrations.RenameIndex(
            model_name='executionhistory',
            new_name='homepage_ex_execute_90b298_idx',
            old_name='homepage_ex_execute_3f2a1c_idx',
        ),
        migrations.RenameIndex(
            model_name='friendship',
            new_name='homepage_fr_from_us_4298ec_idx',
            old_name='homepage_fr_from_us_9f5b15_idx',
        ),
        migrations.RenameIndex(
            model_name='friendship',
            new_name='homepage_fr_to_user_134bee_idx',
            old_name='homepage_fr_to_user_a7c8e6_idx',
        ),
        migrations.RenameIndex(
            model_name='friendship',
            new_name='homepage_fr_created_a9b52d_idx',
            old_name='homepage_fr_created_4d92f1_idx',
        ),
        migrations.RenameIndex(
            model_name='sessionmember',
            new_name='homepage_se_session_124202_idx',
            old_name='homepage_se_session_online_idx',
        ),
        migrations.RenameIndex(
            model_name='sessionmember',
            new_name='homepage_se_user_id_6053c5_idx',
            old_name='homepage_se_user_active_idx',
        ),
        migrations.RenameIndex(
            model_name='sharedcode',
            new_name='homepage_sh_share_i_914925_idx',
            old_name='homepage_sh_share_i_4a5b2e_idx',
        ),
        migrations.RenameIndex(
            model_name='sharedcode',
            new_name='homepage_sh_user_id_8337b9_idx',
            old_name='homepage_sh_user_id_6c8d3f_idx',
        ),
        migrations.RenameIndex(
            model_name='sharedcode',
            new_name='homepage_sh_is_publ_baf0e4_idx',
            old_name='homepage_sh_is_publ_7d9e4a_idx',
        ),
        migrations.RenameIndex(
            model_name='sharedcode',
            new_name='homepage_sh_view_co_6755cc_idx',
            old_name='homepage_sh_view_co_8e0f5b_idx',
        ),
        migrations.RenameIndex(
            model_name='sharedcode',
            new_name='homepage_sh_session_539be1_idx',
            old_name='homepage_sh_session_idx',
        ),
        migrations.RenameIndex(
            model_name='userstatus',
            new_name='homepage_us_is_onli_fa13a1_idx',
            old_name='homepage_us_is_onli_8k9l0m_idx',
        ),
        migrations.AddField(
            model_name='idedirectory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subdirectories', to='homepage.idedirectory'),
        ),
        migrations.AddField(
            model_name='idefile',
            name='directory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='homepage.idedirectory'),
        ),
        migrations.AddField(
            model_name='ideexecutionlog',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='homepage.idefile'),
        ),
        migrations.AddField(
            model_name='ideproject',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ide_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='idefile',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='homepage.ideproject'),
        ),
        migrations.AddField(
            model_name='ideexecutionlog',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_logs', to='homepage.ideproject'),
        ),
        migrations.AddField(
            model_name='idedirectory',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directories', to='homepage.ideproject'),
        ),
        migrations.AddField(
            model_name='ideterminalsession',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terminal_sessions', to='homepage.ideproject'),
        ),
        migrations.AddIndex(
            model_name='ideproject',
            index=models.Index(fields=['user', '-last_accessed'], name='homepage_id_user_id_a53217_idx'),
        ),
        migrations.AddIndex(
            model_name='ideproject',
            index=models.Index(fields=['user', 'is_active'], name='homepage_id_user_id_159286_idx'),
        ),
        migrations.AddIndex(
            model_name='ideproject',
            index=models.Index(fields=['project_id'], name='homepage_id_project_d3c287_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ideproject',
            unique_together={('user', 'name')},
        ),
        migrations.AddIndex(
            model_name='idefile',
            index=models.Index(fields=['project', 'directory'], name='homepage_id_project_2191c9_idx'),
        ),
        migrations.AddIndex(
            model_name='idefile',
            index=models.Index(fields=['project', 'file_type'], name='homepage_id_project_058da5_idx'),
        ),
        migrations.AddIndex(
            model_name='idefile',
            index=models.Index(fields=['project', 'path'], name='homepage_id_project_8c30dd_idx'),
        ),
        migrations.AddIndex(
            model_name='idefile',
            index=models.Index(fields=['-updated_at'], name='homepage_id_updated_04663d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='idefile',
            unique_together={('project', 'path')},
        ),
        migrations.AddIndex(
            model_name='ideexecutionlog',
            index=models.Index(fields=['project', '-executed_at'], name='homepage_id_project_8d2e83_idx'),
        ),
        migrations.AddIndex(
            model_name='ideexecutionlog',
            index=models.Index(fields=['project', 'was_successful'], name='homepage_id_project_53e6fa_idx'),
        ),
        migrations.AddIndex(
            model_name='idedirectory',
            index=models.Index(fields=['project', 'parent'], name='homepage_id_project_84a052_idx'),
        ),
        migrations.AddIndex(
            model_name='idedirectory',
            index=models.Index(fields=['project', 'path'], name='homepage_id_project_2b4aca_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='idedirectory',
            unique_together={('project', 'path')},
        ),
        migrations.AddIndex(
            model_name='ideterminalsession',
            index=models.Index(fields=['project', 'is_active'], name='homepage_id_project_758b3f_idx'),
        ),
        migrations.AddIndex(
            model_name='ideterminalsession',
            index=models.Index(fields=['session_id'], name='homepage_id_session_f08655_idx'),
        ),
    ]
