# Generated by Django 5.2.6 on 2025-10-17 11:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0013_server_serverchannel_serverinvite_servermember_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServerCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("name", models.CharField(max_length=100)),
                ("position", models.IntegerField(default=0)),
                ("is_collapsed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Server Categories",
                "ordering": ["position", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="ServerRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("name", models.CharField(max_length=50)),
                ("color", models.CharField(default="#99AAB5", max_length=7)),
                ("position", models.IntegerField(default=0)),
                ("can_manage_channels", models.BooleanField(default=False)),
                ("can_manage_roles", models.BooleanField(default=False)),
                ("can_kick_members", models.BooleanField(default=False)),
                ("can_ban_members", models.BooleanField(default=False)),
                ("can_manage_messages", models.BooleanField(default=False)),
                ("can_mention_everyone", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-position", "name"],
            },
        ),
        migrations.AddField(
            model_name="serverchannel",
            name="bitrate",
            field=models.IntegerField(default=64),
        ),
        migrations.AddField(
            model_name="serverchannel",
            name="user_limit",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="servermember",
            name="current_voice_channel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="voice_members",
                to="homepage.serverchannel",
            ),
        ),
        migrations.AlterField(
            model_name="serverchannel",
            name="channel_type",
            field=models.CharField(
                choices=[
                    ("text", "Text Channel"),
                    ("voice", "Voice Channel"),
                    ("announcements", "Announcements"),
                ],
                default="text",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="servercategory",
            name="server",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="homepage.server",
            ),
        ),
        migrations.AddField(
            model_name="serverchannel",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="channels",
                to="homepage.servercategory",
            ),
        ),
        migrations.AddField(
            model_name="serverrole",
            name="server",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="custom_roles",
                to="homepage.server",
            ),
        ),
        migrations.AddField(
            model_name="serverchannel",
            name="allowed_roles",
            field=models.ManyToManyField(
                blank=True, related_name="accessible_channels", to="homepage.serverrole"
            ),
        ),
        migrations.AddField(
            model_name="servermember",
            name="custom_roles",
            field=models.ManyToManyField(
                blank=True, related_name="members", to="homepage.serverrole"
            ),
        ),
        migrations.AddIndex(
            model_name="servercategory",
            index=models.Index(
                fields=["server", "position"], name="homepage_se_server__09db03_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="serverrole",
            index=models.Index(
                fields=["server", "position"], name="homepage_se_server__e0c8fa_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="serverrole",
            unique_together={("server", "name")},
        ),
    ]
