# Generated by Django 5.2.6 on 2025-10-16 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0013_server_serverchannel_serverinvite_servermember_and_more'),
    ]