# Generated by Django 5.2.6 on 2025-10-12 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LoginAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                (
                    "attempted_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("successful", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["ip_address", "-timestamp"],
                        name="auth_app_lo_ip_addr_45de65_idx",
                    )
                ],
            },
        ),
    ]
